-- wake-upsystem 完整数据库脚本（Supabase）
-- 用途：收录项目当前用到的全部业务表结构 + 兼容补字段 + 索引/约束
-- 执行方式：在 Supabase SQL Editor 整段执行

begin;

-- =====================================================
-- A) staff_list：员工表
-- =====================================================
create table if not exists public.staff_list (
  id text primary key,
  name text not null,
  password text not null,
  salary numeric(12,2) not null default 0,
  phone text default '',
  salarymethod text default 'alipay',
  salaryaccount text default ''
);

alter table public.staff_list add column if not exists name text;
alter table public.staff_list add column if not exists password text;
alter table public.staff_list add column if not exists salary numeric(12,2);
alter table public.staff_list add column if not exists phone text;
alter table public.staff_list add column if not exists salarymethod text;
alter table public.staff_list add column if not exists salaryaccount text;

update public.staff_list set salary = 0 where salary is null;
update public.staff_list set phone = '' where phone is null;
update public.staff_list set salarymethod = 'alipay' where salarymethod is null or btrim(salarymethod) = '';
update public.staff_list set salaryaccount = '' where salaryaccount is null;

alter table public.staff_list alter column salary set default 0;
alter table public.staff_list alter column phone set default '';
alter table public.staff_list alter column salarymethod set default 'alipay';
alter table public.staff_list alter column salaryaccount set default '';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'chk_staff_salarymethod'
  ) then
    alter table public.staff_list
      add constraint chk_staff_salarymethod
      check (salarymethod in ('alipay', 'wechat', 'bank'));
  end if;
end $$;

create index if not exists idx_staff_list_name on public.staff_list(name);


-- =====================================================
-- B) wake_orders：叫醒订单表
-- =====================================================
create table if not exists public.wake_orders (
  id bigint generated by default as identity primary key,
  waketime text not null,
  phone text not null,
  note text default '',
  amount numeric(12,2) not null default 0,
  status text not null default '待接单',
  serialnumber integer,
  staffid text default '',
  staffname text default '',
  salarysettled boolean not null default false,
  submittime timestamptz not null default now()
);

alter table public.wake_orders add column if not exists waketime text;
alter table public.wake_orders add column if not exists phone text;
alter table public.wake_orders add column if not exists note text;
alter table public.wake_orders add column if not exists amount numeric(12,2);
alter table public.wake_orders add column if not exists status text;
alter table public.wake_orders add column if not exists serialnumber integer;
alter table public.wake_orders add column if not exists staffid text;
alter table public.wake_orders add column if not exists staffname text;
alter table public.wake_orders add column if not exists salarysettled boolean;
alter table public.wake_orders add column if not exists submittime timestamptz;

update public.wake_orders set note = '' where note is null;
update public.wake_orders set amount = 0 where amount is null;
update public.wake_orders set status = '待接单' where status is null or btrim(status) = '';
update public.wake_orders set staffid = '' where staffid is null;
update public.wake_orders set staffname = '' where staffname is null;
update public.wake_orders set salarysettled = false where salarysettled is null;
update public.wake_orders set submittime = now() where submittime is null;

alter table public.wake_orders alter column note set default '';
alter table public.wake_orders alter column amount set default 0;
alter table public.wake_orders alter column status set default '待接单';
alter table public.wake_orders alter column staffid set default '';
alter table public.wake_orders alter column staffname set default '';
alter table public.wake_orders alter column salarysettled set default false;
alter table public.wake_orders alter column submittime set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'chk_wake_orders_status'
  ) then
    alter table public.wake_orders
      add constraint chk_wake_orders_status
      check (status in ('待接单', '进行中', '已完成'));
  end if;
end $$;

create index if not exists idx_wake_orders_submittime on public.wake_orders(submittime desc);
create index if not exists idx_wake_orders_status on public.wake_orders(status);
create index if not exists idx_wake_orders_staffid on public.wake_orders(staffid);


-- =====================================================
-- C) supervise_orders：监督订单表
-- =====================================================
create table if not exists public.supervise_orders (
  id text primary key,
  waketime text not null,
  phone text default '',
  note text default '',
  amount numeric(12,2) not null default 0,
  status text not null default '待接单',
  serialnumber integer,
  staffid text default '',
  staffname text default '',
  salarysettled boolean not null default false,
  submittime timestamptz not null default now()
);

alter table public.supervise_orders add column if not exists waketime text;
alter table public.supervise_orders add column if not exists phone text;
alter table public.supervise_orders add column if not exists note text;
alter table public.supervise_orders add column if not exists amount numeric(12,2);
alter table public.supervise_orders add column if not exists status text;
alter table public.supervise_orders add column if not exists serialnumber integer;
alter table public.supervise_orders add column if not exists staffid text;
alter table public.supervise_orders add column if not exists staffname text;
alter table public.supervise_orders add column if not exists salarysettled boolean;
alter table public.supervise_orders add column if not exists submittime timestamptz;

update public.supervise_orders set phone = '' where phone is null;
update public.supervise_orders set note = '' where note is null;
update public.supervise_orders set amount = 0 where amount is null;
update public.supervise_orders set status = '待接单' where status is null or btrim(status) = '';
update public.supervise_orders set staffid = '' where staffid is null;
update public.supervise_orders set staffname = '' where staffname is null;
update public.supervise_orders set salarysettled = false where salarysettled is null;
update public.supervise_orders set submittime = now() where submittime is null;

alter table public.supervise_orders alter column phone set default '';
alter table public.supervise_orders alter column note set default '';
alter table public.supervise_orders alter column amount set default 0;
alter table public.supervise_orders alter column status set default '待接单';
alter table public.supervise_orders alter column staffid set default '';
alter table public.supervise_orders alter column staffname set default '';
alter table public.supervise_orders alter column salarysettled set default false;
alter table public.supervise_orders alter column submittime set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'chk_supervise_orders_status'
  ) then
    alter table public.supervise_orders
      add constraint chk_supervise_orders_status
      check (status in ('待接单', '进行中', '已完成'));
  end if;
end $$;

create index if not exists idx_supervise_orders_submittime on public.supervise_orders(submittime desc);
create index if not exists idx_supervise_orders_status on public.supervise_orders(status);
create index if not exists idx_supervise_orders_staffid on public.supervise_orders(staffid);


-- =====================================================
-- D) salary_details：余额明细表
-- =====================================================
create table if not exists public.salary_details (
  id text primary key,
  staffid text not null,
  amount numeric(12,2) not null,
  type text not null,
  description text default '',
  createdat timestamptz not null default now(),
  settle_key text,
  order_id text
);

alter table public.salary_details add column if not exists staffid text;
alter table public.salary_details add column if not exists amount numeric(12,2);
alter table public.salary_details add column if not exists type text;
alter table public.salary_details add column if not exists description text;
alter table public.salary_details add column if not exists createdat timestamptz;
alter table public.salary_details add column if not exists settle_key text;
alter table public.salary_details add column if not exists order_id text;

update public.salary_details set description = '' where description is null;
update public.salary_details set createdat = now() where createdat is null;

alter table public.salary_details alter column description set default '';
alter table public.salary_details alter column createdat set default now();

create unique index if not exists uq_salary_details_settle_key
  on public.salary_details(settle_key)
  where settle_key is not null;
create index if not exists idx_salary_details_staffid_createdat
  on public.salary_details(staffid, createdat desc);
create index if not exists idx_salary_details_order_id
  on public.salary_details(order_id);


-- =====================================================
-- E) supervise_leave_requests：监督请假审批主表
-- =====================================================
create table if not exists public.supervise_leave_requests (
  id text primary key,
  order_id text not null,
  order_no text,
  project text,
  target_date date not null,
  leave_type text not null,
  leave_enabled boolean not null default false,
  applicant_id text,
  applicant_name text,
  operator_id text,
  operator_name text,
  status text not null default 'pending',
  updated_at timestamptz not null default now()
);

alter table public.supervise_leave_requests add column if not exists order_id text;
alter table public.supervise_leave_requests add column if not exists order_no text;
alter table public.supervise_leave_requests add column if not exists project text;
alter table public.supervise_leave_requests add column if not exists target_date date;
alter table public.supervise_leave_requests add column if not exists leave_type text;
alter table public.supervise_leave_requests add column if not exists leave_enabled boolean;
alter table public.supervise_leave_requests add column if not exists applicant_id text;
alter table public.supervise_leave_requests add column if not exists applicant_name text;
alter table public.supervise_leave_requests add column if not exists operator_id text;
alter table public.supervise_leave_requests add column if not exists operator_name text;
alter table public.supervise_leave_requests add column if not exists status text;
alter table public.supervise_leave_requests add column if not exists updated_at timestamptz;

update public.supervise_leave_requests set leave_enabled = false where leave_enabled is null;
update public.supervise_leave_requests set status = 'pending' where status is null or btrim(status) = '';
update public.supervise_leave_requests set updated_at = now() where updated_at is null;

alter table public.supervise_leave_requests alter column leave_enabled set default false;
alter table public.supervise_leave_requests alter column status set default 'pending';
alter table public.supervise_leave_requests alter column updated_at set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'chk_supervise_leave_type'
  ) then
    alter table public.supervise_leave_requests
      add constraint chk_supervise_leave_type
      check (leave_type in ('sleep','wake'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'chk_supervise_leave_status'
  ) then
    alter table public.supervise_leave_requests
      add constraint chk_supervise_leave_status
      check (status in ('pending','approved','rejected'));
  end if;
end $$;

create index if not exists idx_slr_applicant_id on public.supervise_leave_requests(applicant_id);
create index if not exists idx_slr_status on public.supervise_leave_requests(status);
create index if not exists idx_slr_updated_at on public.supervise_leave_requests(updated_at desc);
create index if not exists idx_slr_order_target on public.supervise_leave_requests(order_id, target_date);


-- =====================================================
-- F) home_pending_items：Admin 首页待处理事项
-- =====================================================
create table if not exists public.home_pending_items (
  id text primary key,
  kind text not null,
  type text not null,
  order_ref text,
  source text,
  description text,
  payload jsonb not null default '{}'::jsonb,
  done boolean not null default false,
  decision text not null default '',
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  processed_by text
);

alter table public.home_pending_items add column if not exists kind text;
alter table public.home_pending_items add column if not exists type text;
alter table public.home_pending_items add column if not exists order_ref text;
alter table public.home_pending_items add column if not exists source text;
alter table public.home_pending_items add column if not exists description text;
alter table public.home_pending_items add column if not exists payload jsonb;
alter table public.home_pending_items add column if not exists done boolean;
alter table public.home_pending_items add column if not exists decision text;
alter table public.home_pending_items add column if not exists created_at timestamptz;
alter table public.home_pending_items add column if not exists processed_at timestamptz;
alter table public.home_pending_items add column if not exists processed_by text;

update public.home_pending_items set payload = '{}'::jsonb where payload is null;
update public.home_pending_items set done = false where done is null;
update public.home_pending_items set decision = '' where decision is null;
update public.home_pending_items set created_at = now() where created_at is null;

alter table public.home_pending_items alter column payload set default '{}'::jsonb;
alter table public.home_pending_items alter column done set default false;
alter table public.home_pending_items alter column decision set default '';
alter table public.home_pending_items alter column created_at set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'chk_home_pending_decision'
  ) then
    alter table public.home_pending_items
      add constraint chk_home_pending_decision
      check (decision in ('', 'approved', 'rejected'));
  end if;
end $$;

create index if not exists idx_hpi_done_created on public.home_pending_items(done, created_at desc);
create index if not exists idx_hpi_kind on public.home_pending_items(kind);
create index if not exists idx_hpi_created_at on public.home_pending_items(created_at desc);


-- =====================================================
-- G) page_notices：页面公告
-- =====================================================
create table if not exists public.page_notices (
  page text primary key,
  content text not null default '',
  updatedby text,
  updatedat timestamptz not null default now()
);

alter table public.page_notices add column if not exists content text;
alter table public.page_notices add column if not exists updatedby text;
alter table public.page_notices add column if not exists updatedat timestamptz;

update public.page_notices set content = '' where content is null;
update public.page_notices set updatedat = now() where updatedat is null;

alter table public.page_notices alter column content set default '';
alter table public.page_notices alter column updatedat set default now();

create index if not exists idx_page_notices_updatedat on public.page_notices(updatedat desc);

commit;

